# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from .create_text_embeddings_create_text_enbedding_response_text_embedding import (
    CreateTextEmbeddingsCreateTextEnbeddingResponseTextEmbedding,
)
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class CreateTextEmbeddingsCreateTextEnbeddingResponse(UniversalBaseModel):
    engine_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the engine the platform has used to create this embedding.
    """

    text_embedding: typing.Optional[
        CreateTextEmbeddingsCreateTextEnbeddingResponseTextEmbedding
    ] = pydantic.Field(default=None)
    """
    An object that contains a field named `float` which is an array of floating point numbers representing the embedding.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
