# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class ModulesItem(UniversalBaseModel):
    """
    Each element is a dictionary.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The source of information for which the video clip matched your search terms. It can take one of the following values: `conversation`, `visual`, `text_in_video`, and `logo`.
    """

    confidence: typing.Optional[str] = pydantic.Field(default=None)
    """
    The confidence level that the result is accurate.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
