# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class VideoVectorMetadata(UniversalBaseModel):
    """
    An object that contains information about the video.
    """

    filename: typing.Optional[str] = None
    duration: typing.Optional[float] = None
    fps: typing.Optional[float] = None
    width: typing.Optional[int] = None
    height: typing.Optional[int] = None
    size: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
