# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
from .any_to_video_search_any_to_video_search_response_data_item import (
    AnyToVideoSearchAnyToVideoSearchResponseDataItem,
)
import pydantic
from .any_to_video_search_any_to_video_search_response_page_info import (
    AnyToVideoSearchAnyToVideoSearchResponsePageInfo,
)
from ...types.search_pool import SearchPool
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class AnyToVideoSearchAnyToVideoSearchResponse(UniversalBaseModel):
    data: typing.Optional[
        typing.List[AnyToVideoSearchAnyToVideoSearchResponseDataItem]
    ] = pydantic.Field(default=None)
    """
    An array that contains your search results. For each match found, the engine returns the following fields:
    """

    page_info: typing.Optional[AnyToVideoSearchAnyToVideoSearchResponsePageInfo] = (
        pydantic.Field(default=None)
    )
    """
    An object that provides information about pagination.
    """

    search_pool: typing.Optional[SearchPool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
