# This file was auto-generated by Fern from our API Definition.

import typing

AnyToVideoSearchAnyToVideoSearchRequestSearchOptionsItem = typing.Union[
    typing.Literal["visual", "conversation", "text_in_video", "logo"], typing.Any
]
