# This file was auto-generated by Fern from our API Definition.

import typing
from .generate_text_from_video_generate_text_representation_response_one_zero import (
    GenerateTextFromVideoGenerateTextRepresentationResponseOneZero,
)
from .generate_text_from_video_generate_text_representation_response_one_text import (
    GenerateTextFromVideoGenerateTextRepresentationResponseOneText,
)
from .generate_text_from_video_generate_text_representation_response_one_event_type import (
    GenerateTextFromVideoGenerateTextRepresentationResponseOneEventType,
)

GenerateTextFromVideoGenerateTextRepresentationResponseOne = typing.Union[
    GenerateTextFromVideoGenerateTextRepresentationResponseOneZero,
    GenerateTextFromVideoGenerateTextRepresentationResponseOneText,
    GenerateTextFromVideoGenerateTextRepresentationResponseOneEventType,
]
