# This file was auto-generated by Fern from our API Definition.

import typing

GenerateTextFromVideoGenerateGistRequestTypesItem = typing.Union[
    typing.Literal["topic", "hashtag", "title"], typing.Any
]
