# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class GenerateTextFromVideoGenerateTextRepresentationResponseOneZeroMetadata(
    UniversalBaseModel
):
    """
    An object containing metadata about the stream.
    """

    generation_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    A unique identifier for the generation session.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
