# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
from ...types.video_embedding_task import VideoEmbeddingTask
import pydantic
from .create_video_embeddings_list_video_embedding_tasks_response_page_info import (
    CreateVideoEmbeddingsListVideoEmbeddingTasksResponsePageInfo,
)
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class CreateVideoEmbeddingsListVideoEmbeddingTasksResponse(UniversalBaseModel):
    data: typing.Optional[typing.List[VideoEmbeddingTask]] = pydantic.Field(
        default=None
    )
    """
    An array that contains up to `page_limit` video embedding tasks.
    """

    page_info: typing.Optional[
        CreateVideoEmbeddingsListVideoEmbeddingTasksResponsePageInfo
    ] = pydantic.Field(default=None)
    """
    An object that provides information about pagination.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
