# This file was auto-generated by Fern from our API Definition.

import typing

CreateVideoEmbeddingsRetrieveVideoEmbedingResponseMetadataVideoEmbeddingScopeItem = (
    typing.Union[typing.Literal["clip", "video"], typing.Any]
)
