# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
from .classify_video_response_data_item import ClassifyVideoResponseDataItem
import pydantic
from ...types.classify_page_info import ClassifyPageInfo
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class ClassifyVideoResponse(UniversalBaseModel):
    data: typing.Optional[typing.List[ClassifyVideoResponseDataItem]] = pydantic.Field(
        default=None
    )
    """
    An array that contains the response. Each element of the array contains information about a specific video.
    """

    page_info: typing.Optional[ClassifyPageInfo] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
