# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
from ...types.start_time import StartTime
from ...types.end_time import EndTime
import pydantic
from ...types.thumbnail_url import ThumbnailUrl
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class ClassifyVideoResponseDataItemClassesItemClipsItem(UniversalBaseModel):
    start: typing.Optional[StartTime] = None
    end: typing.Optional[EndTime] = None
    score: typing.Optional[float] = pydantic.Field(default=None)
    """
    A number indicating the confidence level that the video clips match the specified class.
    """

    option: typing.Optional[str] = pydantic.Field(default=None)
    """
    Indicates the type of match that the platform has performed.
    """

    prompt: typing.Optional[str] = pydantic.Field(default=None)
    """
    Indicates the prompt that the platform used.
    """

    thumbnail_url: typing.Optional[ThumbnailUrl] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
