# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from .classify_bulk_response_data_item_classes_item import (
    ClassifyBulkResponseDataItemClassesItem,
)
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class ClassifyBulkResponseDataItem(UniversalBaseModel):
    video_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique identifier of the video.
    """

    classes: typing.Optional[typing.List[ClassifyBulkResponseDataItemClassesItem]] = (
        pydantic.Field(default=None)
    )
    """
    An array that contains information about the classes that were detected in your videos.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
