# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class TextToVideoSearchCombinedQueriesMakeSearchRequestRequestFilterDuration(
    UniversalBaseModel
):
    """
    This field filters your search results based on the duration of the video containing the segment that matches your query.

    The following example filters search results to include only the segments from videos with a duration greater than or equal to 600 seconds and less than or equal to 800 seconds:

    ```
    "duration": {
      "gte": 600,
      "lte": 800
    }
    ```
    """

    gte: typing.Optional[float] = pydantic.Field(default=None)
    """
    This field specifies the minimum duration, expressed in seconds, of the video.
    """

    lte: typing.Optional[float] = pydantic.Field(default=None)
    """
    This field specifies the maximum duration, expressed in seconds, of the video.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
