# This file was auto-generated by Fern from our API Definition.

import typing

TextToVideoSearchCombinedQueriesMakeSearchRequestRequestQueryConversationOption = (
    typing.Union[typing.Literal["semantic", "exact_match"], typing.Any]
)
